//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TatExpEntities : DbContext
    {
        public TatExpEntities()
            : base("name=TatExpEntities")
        {
        }
        private static TatExpEntities _context = new TatExpEntities();

        public static TatExpEntities GetContext()
        {
            if (_context == null)
                _context = new TatExpEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Category_prod> Category_prod { get; set; }
        public virtual DbSet<Desire> Desire { get; set; }
        public virtual DbSet<Desire_prod> Desire_prod { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Pick_point> Pick_point { get; set; }
        public virtual DbSet<PP_order> PP_order { get; set; }
        public virtual DbSet<PP_owner> PP_owner { get; set; }
        public virtual DbSet<Prod_order> Prod_order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Shop_cart_Prod> Shop_cart_Prod { get; set; }
        public virtual DbSet<Shoppping_cart> Shoppping_cart { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vender> Vender { get; set; }
    }
}
