//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.PP_order = new HashSet<PP_order>();
            this.Prod_order = new HashSet<Prod_order>();
        }
    
        public int id { get; set; }
        public int Status_id { get; set; }
        public Nullable<System.DateTime> Date_create { get; set; }
        public Nullable<System.DateTime> Date_get { get; set; }
        public int User_id { get; set; }
        public Nullable<int> Empleyee_id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PP_order> PP_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prod_order> Prod_order { get; set; }
    }
}
