//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_cart_Prod
    {
        public int id_shop_cart { get; set; }
        public int id_prod { get; set; }
        public Nullable<int> count { get; set; }
        public int id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shoppping_cart Shoppping_cart { get; set; }
    }
}
